/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/2888f881-a731-45be-82b7-95cd4d21c588 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight botao;
  CloudLight botao2;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  pinMode(D0,OUTPUT);
  pinMode(D1,OUTPUT);
  pinMode(LED_D0,OUTPUT);
  pinMode(LED_D1,OUTPUT);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
 
 if(botao == 1){
    digitalWrite(D0,HIGH);
    digitalWrite(LED_D0,HIGH);
    botao=HIGH;
  }else {
    digitalWrite(D0,LOW);
    digitalWrite(LED_D0,LOW);
    botao=LOW;
    }
  
  
   if(botao2 == 1){
    digitalWrite(D1,HIGH);
    digitalWrite(LED_D1,HIGH);
    botao2=HIGH;
  }else {
    digitalWrite(D1,LOW);
    digitalWrite(LED_D1,LOW);
    botao2=LOW;
    }
  
  
}


/*
  Since Botao is READ_WRITE variable, onBotaoChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onBotaoChange()  {
  // Add your code here to act upon Botao change
}

/*
  Since Botao2 is READ_WRITE variable, onBotao2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onBotao2Change()  {
  // Add your code here to act upon Botao2 change
}